# Generated by Django 3.2.6 on 2021-09-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
                ('admin_html', models.TextField(blank=True, null=True, verbose_name='Верстка для администратора')),
                ('student_html', models.TextField(blank=True, null=True, verbose_name='Верстка для студента')),
                ('flag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Флаг (ответ)')),
            ],
            options={
                'verbose_name': 'Таск',
                'verbose_name_plural': 'Таски',
            },
        ),
    ]
