# Generated by Django 3.2.6 on 2021-09-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='admin_html',
        ),
        migrations.RemoveField(
            model_name='task',
            name='student_html',
        ),
    ]
