# Generated by Django 3.2.6 on 2021-09-05 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0003_auto_20210905_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='TaskSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polygon.task', verbose_name='Таск')),
            ],
            options={
                'verbose_name': 'Решенный таск',
                'verbose_name_plural': 'Решенные таски',
            },
        ),
    ]
