# Generated by Django 3.2.6 on 2021-09-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0005_task_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Номер по порядку'),
        ),
    ]
