# Generated by Django 3.2.6 on 2021-09-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0009_task_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksolve',
            name='date_accepted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия отчета'),
        ),
    ]
