# Generated by Django 3.2.6 on 2021-09-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0011_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
