# Generated by Django 3.2.6 on 2021-09-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0014_auto_20210905_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksolve',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports'),
        ),
        migrations.AlterField(
            model_name='task',
            name='material',
            field=models.ManyToManyField(blank=True, to='polygon.Attachment'),
        ),
    ]
