# Generated by Django 3.2.6 on 2021-09-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0015_auto_20210907_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='admin_html',
            field=models.TextField(blank=True, null=True, verbose_name='Верстка для администратора'),
        ),
    ]
